### ISSUE TITLE
[REQUEST] Wrap code option

### ISSUE THREAD

**Issue by MikhaD** [nyable/obsidian-code-block-enhancer#13]
## Idea
A new option in the plugin settings to toggle line wrapping.
This would wrap lines in code blocks like this:
![image](https://user-images.githubusercontent.com/31388146/143458323-f3ebb4b1-a3b3-4644-ba4f-110144919e58.png)
But the line numbers would match up instead of ignoring the fact that some lines have been wrapped, more like this:
![ideal](https://user-images.githubusercontent.com/31388146/143460106-e75e1b8c-f1ac-45a7-af43-36b186b4827e.png)
## Possible Implementation Idea
At the moment I can wrap the lines in code blocks with the following snippet:
```css
.code-block-wrap pre[class*=language-] {
	overflow-x: hidden !important;
}

.code-block-wrap pre[class*=language-] > code {
	white-space : pre-wrap;
}
```
This is what I did for the first screenshot.

Unfortunately I have not had a chance to look at how you implemented line numbers, so I do not have any suggestions for how to make it compatible with wrapped lines.
