### ISSUE TITLE
Any way to make font size smaller

### ISSUE THREAD

**Issue by swehba** [nyable/obsidian-code-block-enhancer#7]
Love the plug in. So nice to see line numbers in code snippet. My only ask is, is there an easy way to make the font size smaller? I am using the Obsidian Nord theme, and the font size of code blocks when using this plug in is too big — in fact, it's larger than the standard note text.

**Comment by nyable** [comment]
Because different themes may have different font sizes, in order to align line numbers and code blocks, I used `font-size: var(--editor-font-size);` as the code block style, which will be based on the editor font size.
If you want to customize the font size, one of the solutions is create a new file in `Settings-Appearance-CSS snippets`. For example, name it `nord-code-block.css`, and then use higher priority to specify styles or customize some other styles. In the `Obsidian Nord theme`, it may be like:
```css
pre[class*=language-] > code[class*=language-].is-loaded {
  font-size: 0.9em !important;
  line-height: 1.4em !important;
}
pre[class*=language-] {
  font-size: 0.9em!important;
  line-height: 1.4em!important;
}
.code-block-linenum-wrap {
  font-size: 0.9em!important;
  line-height: 1.4em!important;
}
```
